---
- name: tesint the file
  hosts: localhost
  tasks: 
    - name: display the messgae
      debug:
        msg: "Welcome"
      register: display

    - debug: var=display

    - name: Display Python Interpreter
      debug:
        var: ansible_python_interpreter

    - name: Debug environment variables
      command: env
      register: env_output


    - debug: var=env_output

    - name: whoami
      command: whoami
      register: user_output

    - name: user details
      shell: cat /etc/passwd
      
    - name: work directory
      shell: pwd

    - name: env var
      shell: echo $VIRTUAL_ENV

    - debug: var=user_output

    - name: Copy the Python script
      copy:
        src: diskutilization.py
        dest: /tmp/diskutilization.py
        mode: "0755"

    - name: Capture Screenshot and Send Email
      command: python3 /tmp/diskutilization.py
      register: utilize_output

    - debug: var=utilize_output.stdout

    #- name: Clean up Python script
      #file:
        #path: /tmp/diskutilization.py
        #state: absent
