---
- name: tesint the file
  hosts: localhost
  tasks: 
    - name: display the messgae
      debug:
        msg: "Welcome"
      register: display

    - debug: var=display

    - name: Copy the Python script
      copy:
        src: diskutilization.py
        dest: /tmp/diskutilization.py
        mode: "0755"

    - name: Capture Screenshot and Send Email
      command: python3 /tmp/diskutilization.py
      register: utilize_output

    - debug: var=utilize_output

    - name: Clean up Python script
      file:
        path: /tmp/diskutilization.py
        state: absent
