---
- name: tesint the file
  hosts: localhost
  tasks: 
    - name: display the messgae
      debug:
        msg: "Welcome"
      register: display

    - debug: var=display

    - name: Copy the Python script
      copy:
        src: aws_s3_screenshot.py
        dest: /tmp/aws_s3_screenshot.py
        mode: "0755"

    - name: Capture Screenshot and Send Email
      command: python3 /tmp/aws_s3_screenshot.py

    - name: Clean up Python script
      file:
        path: /tmp/aws_s3_screenshot.py
        state: absent
